spring:
    profiles: default
    datasource:
        initialize: false
    batch:
        job:
            enabled: false # disable jobs from running upon start-up

# Tomcat server port
server:
    port: 9003

datasource:
    integration:
        dataSourceClassName: com.mysql.jdbc.jdbc2.optional.MysqlDataSource
        url: jdbc:mysql://192.168.1.7/db
        username: root
        password: 123456

file:
  path: D:\ares\spring-integration-jdbc\tmp
  name: file_name.csv
  pollInterval: 600000

batch:
  size: 5000
  threads: 4

# Unit tests
---
spring:
    profiles: test